# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: catalog_dev
  pool: 5
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: catalog_test
  pool: 5
  username: brusmax
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: catalog_production
  pool: 5
  username: brusmax
  password:
  host: localhost
