# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: catalog_dev
  pool: 5
  host: localhost

test: &TEST
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: catalog_test
  pool: 5
  username: brusmax
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: utf8
  database: postgres://miqxaoisynywgp:G3b5QE883vX_4ZzXiEwi3Q5Mjf@ec2-54-225-156-230.compute-1.amazonaws.com:5432/d2u59hf8oabe59
