Category.create!([
  {name: "Man"},
  {name: "Girls"}
])
Product.create!([
  {name: "Cat dress a tshirt", image: "MG_0823-682x1024.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Beaver", image: "MG_0249.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Paliacate Bag", image: "MG_0776.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Wild charge", image: "MG_0289.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Leopard boy", image: "MG_0525.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: " monkey scarf", image: "MG_0242.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "London", image: "MG_0745.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Fuck", image: "MG_0284.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Nopales", image: "MG_1003.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mexican death", image: "MG_0442.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Blue tie", image: "MG_0079.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Death rebel", image: "MG_0552.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Lata lion", image: "MG_0058.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tacos", image: "MG_0041.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Yeti", image: "MG_0097.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "One Guey", image: "MG_0173.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Apache", image: "MG_0210.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Happy box", image: "MG_0602-copia.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "striped bag", image: "MG_0202.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Militar Dog", image: "MG_0361.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hard lion", image: "MG_0168.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Paliacate bag ", image: "MG_0313.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hot dog hand", image: "MG_0588.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Blue Pirate", image: "MG_0413.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Guitar bird", image: "MG_0571.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Leopard Ride", image: "MG_0421.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Starwars", image: "IMG_3201-682x1024.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Scarecrow", image: "MG_0393.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Screw", image: "MG_0380.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Somoking thorax", image: "MG_0387.jpg", price: 28.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Pinocho", image: "IMG_9913-682x1024.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "King Lion", image: "MG_0357.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Franky", image: "MG_0349.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Monday", image: "MG_0334.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Legs", image: "MG_0467.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Kiss my...", image: "MG_0613.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Subliminal tie", image: "MG_0856.jpg", price: 27.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Marie Flag", image: "MG_0217.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Beret Death", image: "MG_0438.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Apache muscles", image: "MG_7892-682x1024.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Death Eng Flag", image: "MG_0139.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "David", image: "MG_0114.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Girl Mask", image: "MG_0103.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Dog Gloves", image: "MG_0083.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Flag Hand", image: "MG_0055.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "King Death", image: "MG_0012.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Clown", image: "MG_0146.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Girl cat", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Rasta Lion", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Snake", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hand Bone", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Cassettes", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tiger Miami", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "USA Death", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Brown tiger", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Gallero", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Selfie bones", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Jacket Bone", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Street Party", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Death Carts", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Apache Bones", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Skull chain", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Zombie", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "X-ray Death", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Head bones", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Capi Tohrax", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Guazon head", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tiger", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Super A", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "earhquake case", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tie Panter", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Oxigen Jacket", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Plate Stars", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Metal Headphones", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Like friday", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Rasta Lion", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tiger Gray", image: "MG_0473.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Subliminal Jacket", image: "MG_0473.jpg", price: 27.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Follow me good girls", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hecho Desmadre", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mariachi", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Guitar Bones", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Frack", image: "MG_0473.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "monkey glases", image: "MG_0473.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tie and Sack", image: "MG_0473.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]}


])
