Category.create!([
  {name: "Man"},
  {name: "Girls"}
])
Product.create!([
  {name: "Cat dress a tshirt", image: "MG_0823-682x1024.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Beaver", image: "MG_0249.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Paliacate Bag", image: "MG_0776.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Wild charge", image: "MG_0289.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Leopard boy", image: "MG_0525.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: " monkey scarf", image: "MG_0242.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "London", image: "MG_0745.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Fuck", image: "MG_0284.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Nopales", image: "MG_1003.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mexican death", image: "MG_0442.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Blue tie", image: "MG_0079.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Death rebel", image: "MG_0552.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Lata lion", image: "MG_0058.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tacos", image: "MG_0041.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Yeti", image: "MG_0097.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "One Guey", image: "MG_0173.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Apache", image: "MG_0210.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Happy box", image: "MG_0602-copia.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "striped bag", image: "MG_0202.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Militar Dog", image: "MG_0361.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hard lion", image: "MG_0168.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Paliacate bag ", image: "MG_0313.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hot dog hand", image: "MG_0588.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Blue Pirate", image: "MG_0413.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Guitar bird", image: "MG_0571.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Leopard Ride", image: "MG_0421.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Starwars", image: "IMG_3201-682x1024.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Scarecrow", image: "MG_0393.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Screw", image: "MG_0380.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Somoking thorax", image: "MG_0387.jpg", price: 28.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Pinocho", image: "IMG_9913-682x1024.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "King Lion", image: "MG_0357.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Franky", image: "MG_0349.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Monday", image: "MG_0334.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Legs", image: "MG_0467.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Kiss my...", image: "MG_0613.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Subliminal tie", image: "MG_0856.jpg", price: 27.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Marie Flag", image: "MG_0217.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Beret Death", image: "MG_0438.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Apache muscles", image: "MG_7892-682x1024.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Death Eng Flag", image: "MG_0139.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "David", image: "MG_0114.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Girl Mask", image: "MG_0103.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Dog Gloves", image: "MG_0083.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Flag Hand", image: "MG_0055.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "King Death", image: "MG_0012.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Clown", image: "MG_0146.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Girl cat", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Rasta Lion", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Snake", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hand Bone", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Cassettes", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tiger Miami", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "USA Death", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Brown tiger", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Gallero", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Selfie bones", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Jacket Bone", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Street Party", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Death Carts", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Apache Bones", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Skull chain", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Zombie", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "X-ray Death", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Head bones", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Capi Tohrax", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Guazon head", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tiger", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Super A", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "earhquake case", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tie Panter", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Oxigen Jacket", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Plate Stars", image: "MG_0473.jpg", price: 21.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Metal Headphones", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Like friday", image: "MG_0473.jpg", price: 25.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Rasta Lion", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tiger Gray", image: "MG_0473.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Subliminal Jacket", image: "MG_0473.jpg", price: 27.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Follow me good girls", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hecho Desmadre", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mariachi", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Guitar Bones", image: "MG_0473.jpg", price: 20.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Frack", image: "MG_0473.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "monkey glases", image: "MG_0473.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tie and Sack", image: "MG_0473.jpg", price: 22.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Besibol Coach", image: "MG_1458.jpg", price: 55.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Beisbol A Varsity", image: "MG_1419.jpg", price: 53.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Moon wolf", image: "MG_1469.jpg", price: 50.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Light Skeleton", image: "MG_1607.jpg", price: 50.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Sex Love", image: "MG_1439.jpg", price: 50.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Black Guitar", image: "MG_1490.jpg", price: 53.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "England Dog", image: "MG_1500.jpg", price: 53.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Black Skeleton", image: "MG_1536.jpg", price: 53.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Fuck cuffs", image: "MG_1667.jpg", price: 53.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Death Jacket", image: "MG_1539.jpg", price: 55.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Bull Dog", image: "MG_4788-682x1024.jpg", price: 50.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Beisbol college", image: "713x1024.jpg", price: 55.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Esterum", image: "Esternon-623x1024.jpg", price: 47.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Pocker", image: "Pocker-759x1024.jpg", price: 55.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Aditivo NY", image: "Aditivo-720x1024.jpg", price: 47.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "England", image: "MG_9246-646x1024.jpg", price: 48.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Capitan A", image: "MG_9187-682x1024.jpg", price: 53.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mask", image: "IMG_4351-682x1024.jpg", price: 53.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Batman", image: "sudadera_batman.jpg", price: 47.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Guason", image: "suadera_guason.jpg", price: 45.0, status: true, category_id: 1, picture: nil, sizes: ["S", "M", "L", "XL"]},
  #Girls
  {name: "Tigers", image: "test.jpg", price: 55.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mouth", image: "MG_1708.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Wings heart", image: "MG_1767.jpg", price: 21.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Coca cola", image: "IMG_0094.jpg", price: 22.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Rebelious", image: "MG_1719.jpg", price: 25.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "With Tiger", image: "MG_0862.jpg", price: 21.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mostache", image: "MG_1754.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Rebel #1", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Foil Flag", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Blue baby", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Flag Guitars", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Aditivo", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Kissme", image: "test.jpg", price: 25.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Twist Girl", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Music Gitar", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Stones", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Heart Stripes", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Heartbreakers", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hands", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Cat", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Doll", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Subliminal flag", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Pollo con mole", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Blue Tiger eye", image: "test.jpg", price: 21.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "London heart", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Geen flowers", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Hamburger", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Love Bici", image: "test.jpg", price: 21.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Rock star", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Zebra", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Property of my boyfriend", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Skeleton Hand", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Navajos", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Cat blue lenses", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "A 1973", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Pink flowers", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Cat Paliacate", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Baby Esterum", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mewsic", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Lips Flag", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "University tiger", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Lady, cat, tiger", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Skeleton / Navajo", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Lace Skeleton", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Daisy", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Feathers", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Subliminal Guitar Flag", image: "test.jpg", price: 23.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Baby Skeleton", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Red Mouth", image: "test.jpg", price: 19.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Ribs", image: "test.jpg", price: 21.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tree", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Leopard", image: "test.jpg", price: 21.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tank top", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Mariachi", image: "test.jpg", price: 19.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Words", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tank top Hot Mess", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "EU Flag", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Heart Heand mickey", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Lungs", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Love", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Full Flag", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Love", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Lenses Lion", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Leopard Thunder", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Tiger", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Corona", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "London", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Girl Vintage", image: "test.jpg", price: 21.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Choping Taim", image: "test.jpg", price: 20.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Broadway", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Flower Aditivo", image: "test.jpg", price: 31.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "EU Flag", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Love", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "White Love", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Love love love", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Gray Flag", image: "test.jpg", price: 30.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Sequins Love", image: "test.jpg", price: 31.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "Bar Code", image: "test.jpg", price: 45.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "England Flag", image: "test.jpg", price: 45.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]},
  {name: "monkey", image: "test.jpg", price: 45.0, status: true, category_id: 2, picture: nil, sizes: ["S", "M", "L", "XL"]}

])
